'use client';
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import { Noto_Sans_KR } from "next/font/google";

// Google 폰트 불러오기
const bold = Noto_Sans_KR({
  weight: "500",
  display: "fallback",
  subsets: ["latin"],
  style: "normal",
  variable: "--noto-sans_KR-bold",
  fallback: ["system-ui"],
});


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body
        className={bold.className}
      >
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
